### ISSUE TITLE
Check descriptions with curly brackets are not compatible with logger::formatter_glue (the default formatter)

### ISSUE THREAD

**Issue by lkell** [shunsambongi/chex#26]
When no formatters are manually set, the following line causes an error:

`chex::check_that(1, chex::result(TRUE, "description with {curly brackets}"))`
#> Error in value[[3L]](cond): `glue` failed in `formatter_glue` on:
#> 
#>   chr "description with {curly brackets}" 
#> 
#> Raw error message:
#> 
#>  <text>:1:7: unexpected symbol
#> 1: curly brackets
#>           ^ 
#> 
#> Please consider using another `log_formatter` or `skip_formatter` on strings with curly braces.

Using a different formatter works:
```
logger::log_formatter(logger::formatter_logging, namespace = "chex")
chex::check_that(1, chex::set_description(TRUE, "description with {curly brackets}"))
```

-- RESULTS -------------------------------------------------------------- [1] --
√ PASS ... description with {curly brackets}

**Comment by shunsambongi** [comment]
From the logger docs (emphasis added):

> Please note that setting the formatter function via ?log_formatter should **NOT** be left to the R package end-users, as the log message formatter is specific to your logging calls, so that should be decided by the R package author. Feel free to pick any formatter function (eg glue, sprintf, paste or something else), and set that via ?log_formatter when your R package is loaded. All other parameters of your logger will inherit from the global namespace – set by your R package’s end user.

The formatter should be set by the package, not the end-user. I should be able to fix this in the package.
